### PR TITLE
ACL fixes

### PR DESCRIPTION
**Pull request by nacc**
One bugfix and two nice-to-haves related to reservations.

### CODE REVIEW

**Comment by lmr** [comment]
@nacc, your patches are breaking the unittests, and therefore, must be updated to include fixes.

**Comment by nacc** [comment]
Lucas, will fix tomorrow and update the branch! Sorry about that -- makes sense, though, I'm changing a core field :)

**Comment by nacc** [comment]
@lmr, just pushed out a new set that includes the unittest fixes, I think. We'll see how the CI goes.

**Comment by lmr** [comment]
@nacc, awesome! It's looking pretty good.

**Pull request merged**
